# -*- coding: utf-8 -*-
"""
/***************************************************************************
 finddata
                                 A QGIS plugin
 find any spatial data
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-01-18
        copyright            : (C) 2021 by Viacheslav Zamaraev
        email                : zamaraev@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the MIT License.
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load finddata class from file finddata.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .finddata import finddata
    return finddata(iface)
