# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'finddata_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_finddataDialogBase(object):
    def setupUi(self, finddataDialogBase):
        finddataDialogBase.setObjectName("finddataDialogBase")
        finddataDialogBase.resize(469, 452)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(finddataDialogBase.sizePolicy().hasHeightForWidth())
        finddataDialogBase.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        finddataDialogBase.setWindowIcon(icon)
        finddataDialogBase.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        finddataDialogBase.setSizeGripEnabled(True)
        finddataDialogBase.setModal(True)
        self.gridLayout_2 = QtWidgets.QGridLayout(finddataDialogBase)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(finddataDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tabLog = QtWidgets.QWidget()
        self.tabLog.setObjectName("tabLog")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tabLog)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lvLog = QtWidgets.QListWidget(self.tabLog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lvLog.sizePolicy().hasHeightForWidth())
        self.lvLog.setSizePolicy(sizePolicy)
        self.lvLog.setObjectName("lvLog")
        self.gridLayout_3.addWidget(self.lvLog, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabLog, "")
        self.tabVector = QtWidgets.QWidget()
        self.tabVector.setObjectName("tabVector")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tabVector)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tableWidget = QtWidgets.QTableWidget(self.tabVector)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(10)
        self.tableWidget.setObjectName("tableWidget")
        self.gridLayout_4.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabVector, "")
        self.tabStat = QtWidgets.QWidget()
        self.tabStat.setObjectName("tabStat")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tabStat)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tabWidget.addTab(self.tabStat, "")
        self.gridLayout_2.addWidget(self.tabWidget, 1, 0, 1, 2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btnApply = QtWidgets.QPushButton(finddataDialogBase)
        self.btnApply.setObjectName("btnApply")
        self.horizontalLayout.addWidget(self.btnApply)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout_2.addLayout(self.verticalLayout, 3, 0, 1, 2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.edtFolder = QtWidgets.QLineEdit(finddataDialogBase)
        self.edtFolder.setObjectName("edtFolder")
        self.gridLayout.addWidget(self.edtFolder, 0, 1, 1, 1)
        self.btnSelectFolder = QtWidgets.QToolButton(finddataDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSelectFolder.sizePolicy().hasHeightForWidth())
        self.btnSelectFolder.setSizePolicy(sizePolicy)
        self.btnSelectFolder.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.btnSelectFolder.setObjectName("btnSelectFolder")
        self.gridLayout.addWidget(self.btnSelectFolder, 0, 3, 1, 1)
        self.label = QtWidgets.QLabel(finddataDialogBase)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 2)
        self.line = QtWidgets.QFrame(finddataDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 2, 0, 1, 2)

        self.retranslateUi(finddataDialogBase)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(finddataDialogBase)

    def retranslateUi(self, finddataDialogBase):
        _translate = QtCore.QCoreApplication.translate
        finddataDialogBase.setWindowTitle(_translate("finddataDialogBase", "finddata"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabLog), _translate("finddataDialogBase", "Log"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabVector), _translate("finddataDialogBase", "Vector"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabStat), _translate("finddataDialogBase", "Statistics"))
        self.btnApply.setText(_translate("finddataDialogBase", "Apply"))
        self.edtFolder.setToolTip(_translate("finddataDialogBase", "Please scpecify folder or disk"))
        self.btnSelectFolder.setStatusTip(_translate("finddataDialogBase", "Please Select Root Folder for scaning"))
        self.btnSelectFolder.setText(_translate("finddataDialogBase", "..."))
        self.label.setText(_translate("finddataDialogBase", "<html><head/><body><p>Folder</p></body></html>"))

